# Site settings
title: Matthew Crichton
twitter_username: selpathor
name: Matthew Crichton

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/selpathor
 - title: StackOverflow
   url: https://stackoverflow.com/users/7343176/matthew-crichton
 - title: LinkedIn
   url: https://www.linkedin.com/in/matthewcrichton/

#Any buzzword skills you want to include
skills:
 - Python
 - Django
 - Java
 - Spring
 - C#
 - HTML/CSS
 - JQuery/Javascript
 - SQL
 - Full Stack

#Work experience is required
roles:
 - title: Unity Developer
   start: 2018
   end: Ongoing
   employer: Legendary Realms Productions
   description: Aiding in the development of the Supershow Card game App, a Unity based port of the collectible card game.
 - title: Python Instructor
   start: 2017
   end: 2018
   employer: Practical Programming
   description: Taught students the basics of software development and Python. Assisted in the development of a comprehensive curriculum 
 - title: Lead Developer Intern
   start: 2016
   end: 2017
   employer: InSpirAve
   description: Drove the development of the Inspirave website and application with Java, Spring, and Wordpress.	Developed a development strategy for Inspirave, a South by Southwest Accelerator Finalist.

#Education is required
education:
 - level: Bachelor of Science
   date: 2014
   subject: Natural Science and Math with Minors in Computer Science and Biology
   school: Dowling College


#List of interesting Github repo/projects to include - optional
github:
 - LRProduction/SuperShow
 - selpathor/geniusCreator
 - selpathor/Calendar-Attempt-1

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/7343176/matthew-crichton
   flairimageurl: https://stackoverflow.com/users/flair/7343176.png
   
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: Python is my primary programming language. I have been programming in Python on and off for almost 3 years. While it is not my most experienced language I have found to it be my favorite.<br/><br/>
   <strong>Java</strong>: Although Python is my favorite language Java is the language I am most proficient in. I began learning Java in High School and I have been using it ever since. 
